### ISSUE TITLE
DIVERT_TO_PRIVATE broken

### ISSUE THREAD

**Issue by zoni** [errbotio/err-backend-gitter#4]
Commands listed in `DIVERT_TO_PRIVATE` throw an exception when being issued to the bot:

```
2016-02-28 17:43:19,153 DEBUG    yapsy_loaded_plugin_Gitter_0 POST url= https://api.gitter.im/v1/rooms/529c6c56ed5ab0b3bf04d8ae/chatMessage, data = {"text": "## Yes I am alive...\n\n\n\n### Plugins\n\nStatus  | Name                    \n------- | ----------------------- \n**A** | ACLs\n**A** | Backup\n**A** | ChatRoom\n**A** | Health\n**A** | Help\n**A** | Plugins\n**A** | Utils\n**A** | VersionChecker\n**A** | Webserver\n\n\n**A** = Activated, **D** = Deactivated, **B** = Blacklisted, **C** = Needs to be configured\n\nLoad 0.0, 0.01, 0.05\nGC 0->386 1->5 2->2"}
2016-02-28 17:43:19,155 INFO     requests.packages.urllib3.connectionpool Starting new HTTPS connection (1): api.gitter.im
2016-02-28 17:43:19,559 DEBUG    requests.packages.urllib3.connectionpool "POST /v1/rooms/529c6c56ed5ab0b3bf04d8ae/chatMessage HTTP/1.1" 404 85
2016-02-28 17:43:19,562 ERROR    errbot.errBot             An error happened while processing a message ("!status"): Traceback (most recent call last):
  File "/srv/errbot/virtualenv/lib/python3.4/site-packages/errbot/errBot.py", line 462, in _execute_and_send
    self.send_simple_reply(mess, self.process_template(template_name, reply), private)
  File "/srv/errbot/virtualenv/lib/python3.4/site-packages/errbot/errBot.py", line 214, in send_simple_reply
    self.split_and_send_message(self.build_reply(mess, text, private))
  File "/srv/errbot/virtualenv/lib/python3.4/site-packages/errbot/errBot.py", line 193, in split_and_send_message
    self.send_message(partial_message)
  File "/srv/errbot/extra_backends/err-backend-gitter/gitter.py", line 306, in send_message
    self.writeAPIRequest('rooms/%s/chatMessage' % mess.to.idd, content)
  File "/srv/errbot/extra_backends/err-backend-gitter/gitter.py", line 231, in writeAPIRequest
    raise Exception("Server returned an error %d:%s" % (r.status_code, r.text))
Exception: Server returned an error 404:Cannot POST /v1/rooms/529c6c56ed5ab0b3bf04d8ae/chatMessage

"
Traceback (most recent call last):
  File "/srv/errbot/virtualenv/lib/python3.4/site-packages/errbot/errBot.py", line 462, in _execute_and_send
    self.send_simple_reply(mess, self.process_template(template_name, reply), private)
  File "/srv/errbot/virtualenv/lib/python3.4/site-packages/errbot/errBot.py", line 214, in send_simple_reply
    self.split_and_send_message(self.build_reply(mess, text, private))
  File "/srv/errbot/virtualenv/lib/python3.4/site-packages/errbot/errBot.py", line 193, in split_and_send_message
    self.send_message(partial_message)
  File "/srv/errbot/extra_backends/err-backend-gitter/gitter.py", line 306, in send_message
    self.writeAPIRequest('rooms/%s/chatMessage' % mess.to.idd, content)
  File "/srv/errbot/extra_backends/err-backend-gitter/gitter.py", line 231, in writeAPIRequest
    raise Exception("Server returned an error %d:%s" % (r.status_code, r.text))
Exception: Server returned an error 404:Cannot POST /v1/rooms/529c6c56ed5ab0b3bf04d8ae/chatMessage

2016-02-28 17:43:19,563 DEBUG    yapsy_loaded_plugin_Gitter_0 bf body = Computer says nooo. See logs for details:
 Server returned an error 404:Cannot POST /v1/rooms/529c6c56ed5ab0b3bf04d8ae/chatMessage

2016-02-28 17:43:19,567 DEBUG    yapsy_loaded_plugin_Gitter_0 af body = Computer says nooo. See logs for details:
 Server returned an error 404:Cannot POST /v1/rooms/529c6c56ed5ab0b3bf04d8ae/chatMessage

2016-02-28 17:43:19,568 DEBUG    yapsy_loaded_plugin_Gitter_0 POST url= https://api.gitter.im/v1/rooms/529c6c56ed5ab0b3bf04d8ae/chatMessage, data = {"text": "Computer says nooo. See logs for details:\n Server returned an error 404:Cannot POST /v1/rooms/529c6c56ed5ab0b3bf04d8ae/chatMessage\n"}
2016-02-28 17:43:19,569 INFO     requests.packages.urllib3.connectionpool Starting new HTTPS connection (1): api.gitter.im
```

**Comment by zoni** [comment]
This is no longer quite as broken. It is now simply being ignored rather than causing the bot to blow up entirely. Likely a side effect of a04e6119bdea5990faecd4e98be9e609e057beb5.
